.TH xiate 1 "2018-01-14" "xiate" "User Commands"
.\" --------------------------------------------------------------------
.SH NAME
xiate \- terminal emulator (daemon)
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\fBxiate\fP [\fIsuffix\fP]
.\" --------------------------------------------------------------------
.SH DESCRIPTION
\fBxiate\fP is the daemon component of xiate. This program must be
running in order to launch terminal windows.
.\" --------------------------------------------------------------------
.SH OPTIONS
\fBxiate\fP knows exactly one command line argument which is optional:
.TP
\fIsuffix\fP
\fBxiate\fP creates a UNIX socket on which it listens for incoming
connections. This socket is named \(lqxiate-\fIsuffix\fP\(rq.
\fIsuffix\fP defaults to \fBmain\fP.
.\" --------------------------------------------------------------------
.SH "KEY BINDINGS"
In windows launched by \fBxiate\fP, you can use the following key
bindings.
.P
.TP
\fBCtrl + Keypad_Plus\fP
Increase font size.
.TP
\fBCtrl + Keypad_Minus\fP
Decrease font size.
.TP
\fBCtrl + Keypad_0\fP
Reset font size.
.TP
\fBCtrl + Keypad_\fP\fIn\fP
Switch to another font, where \fIn\fP is 1 through 9. Fonts are defined
in \fIconfig.h\fP. This also resets the font size.
.TP
\fBCtrl + Shift + F\fP
Dumps the terminal history to a file and calls a tool you specified in
\fIconfig.h\fP.
.TP
\fBCtrl + Shift + C\fP
Copy currently selected text into clipboard.
.TP
\fBCtrl + Shift + V\fP
Paste from clipboard.
.TP
\fBRight mouse button\fP
When hovering over links, you can use this button to invoke your link
handler. The name of this tool is defined in \fIconfig.h\fP.
\fBargv[1]\fP will be set to \fBexplicit\fP for explicit hyperlinks or
to \fBmatched\fP if a link has been detected via the regular expression
(also see the comments in \fIconfig.h\fP).
.\" --------------------------------------------------------------------
.SH ENVIRONMENT
.P
.TP
.B DISPLAY
Points to the X11 display on which to open terminal windows.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBxiate\fP is released under the MIT license. See the accompanying
\fILICENSE\fP file.
.\" --------------------------------------------------------------------
.SH HISTORY
\fBxiate\fP was originally written by Peter Hofmann. The project was
started in September 2015.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
See \fBxiatec\fP(1) for the client.
.P
Other terminal emulators include:
.BR sakura (1),
.BR st (1),
.BR urxvt (1),
.BR xterm (1).
