.TH xiate 1 "2015-09-21" "xiate" "User Commands"
.\" --------------------------------------------------------------------
.SH NAME
xiate \- terminal emulator (daemon)
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\fBxiate\fP [\fIsuffix\fP]
.\" --------------------------------------------------------------------
.SH DESCRIPTION
\fBxiate\fP is the daemon component of xiate. This program must be run
in order to actually launch terminal windows.
.\" --------------------------------------------------------------------
.SH OPTIONS
\fBxiate\fP knows exactly one command line argument which is optional:
.TP
\fIsuffix\fP
\fBxiate\fP creates a UNIX socket on which it listens for incoming
connections. This socket is named \(lqxiate-\fIsuffix\fP\(rq.
\fIsuffix\fP defaults to \fBmain\fP.
.\" --------------------------------------------------------------------
.SH ENVIRONMENT
.P
.TP
.B DISPLAY
Points to the X11 display on which to open terminal windows.
.TP
.B XDG_RUNTIME_DIR
Specifies the location of the UNIX socket.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBxiate\fP is released as \(lqPIZZA-WARE\(rq. See the accompanying
\fILICENSE\fP file.
.\" --------------------------------------------------------------------
.SH HISTORY
\fBxiate\fP was originally written by Peter Hofmann. The project was
started in September 2015.
.\" --------------------------------------------------------------------
.SH "SEE ALSO"
See \fBxiatec\fP(1) for the client.
.P
Other terminal emulators include:
.BR sakura (1),
.BR st (1),
.BR urxvt (1),
.BR xterm (1).
