#!/bin/bash

# XTerm'ish arguments
class=
execute=()
hold=0
name=
title=

# Our own arguments
suffix=main

while (( $# > 0 ))
do
    case "$1" in
        -class)
            class=$2
            shift
            ;;
        -e)
            shift
            execute=("$@")
            ;;
        -hold)
            hold=1
            ;;
        -name)
            name=$2
            shift
            ;;
        -title)
            title=$2
            shift
            ;;
        --suffix)
            suffix=$2
            shift
            ;;
    esac
    shift
done

(
    printf "OC$PWD\000"
    [[ -n "$class" ]] && printf "Oc$class\000"
    [[ -n "$name" ]] && printf "On$name\000"
    [[ -n "$title" ]] && printf "Ot$title\000"
    (( hold )) && printf 'H'
    if (( "${#execute[@]}" > 0 ))
    then
        for i in "${execute[@]}"
        do
            printf "A$i\000"
        done
    fi
) | socat - UNIX:/var/run/user/$(id -u)/muted-"$suffix",retry=10
