#!/bin/bash

# XTerm'ish arguments
class=
execute=()
hold=0
name=
title=

# Our own arguments
suffix=main

while (( $# > 0 ))
do
    case "$1" in
        -class)
            class=$2
            shift
            ;;
        -e)
            shift
            execute=("$@")
            ;;
        -hold)
            hold=1
            ;;
        -name)
            name=$2
            shift
            ;;
        -title)
            title=$2
            shift
            ;;
        --suffix)
            suffix=$2
            shift
            ;;
    esac
    shift
done

(
    printf "OC%s\000" "$PWD"
    [[ -n "$class" ]] && printf "Oc%s\000" "$class"
    [[ -n "$name" ]] && printf "On%s\000" "$name"
    [[ -n "$title" ]] && printf "Ot%s\000" "$title"
    (( hold )) && printf 'H'
    if (( "${#execute[@]}" > 0 ))
    then
        for i in "${execute[@]}"
        do
            printf "A%s\000" "$i"
        done
    fi
) | socat - UNIX:/var/run/user/$(id -u)/xiate-"$suffix",retry=10 \
    >/dev/null 2>&1
